### PR TITLE
Fix TODOs

### LINKED ISSUE #70: Update /webhook endpoint response to use a JSON format
Reference: https://github.com/Huemul/subilo/blob/master/src/main.rs#L105

### PR DESCRIPTION
**Pull request by gillchristian**
Closes #70 

Fixed the TODOs and removed usage of some `.unwrap()`

### CODE REVIEW

File: src/auth.rs [hunk 1]
```diff
@@ -90,12 +89,17 @@ pub fn create_token(
     .map_err(|err| SubiloError::Authenticate { source: err })
 }
 
-// TODO: Migrate result to SubiloError and handle app data context unwrap.
```
Comment (gillchristian) [inline src/auth.rs:93]: This function is used as a middleware and it expects the returns `Result<ServiceRequest, actix_web::Error>` so I couldn't change it to SubiloError
